# Generated by Django 5.0.4 on 2026-02-02 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_externalteam_role_alter_externalteam_client_org'),
        ('projects', '0002_alter_project_external_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('On Time', 'On Time'), ('In Progress', 'In Progress'), ('Delayed', 'Delayed'), ('Overdue', 'Overdue'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('task_score', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_file', models.FileField(blank=True, null=True, upload_to='tasks/assignments/')),
                ('completion_file', models.FileField(blank=True, null=True, upload_to='tasks/completions/')),
                ('source_module', models.CharField(default='DIRECT', max_length=50)),
                ('source_ref_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_assigned', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL)),
                ('client_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_tasks', to='clients.client')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='projects.project')),
            ],
        ),
    ]
