# Generated by Django 5.0.4 on 2026-02-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_add_ats_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='source_ref_id',
        ),
    ]
