# Generated by Django 5.0.4 on 2026-02-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_source_ref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='source_ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
