# Generated by Django 5.0.4 on 2026-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0012_alter_task_related_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="repeat_day",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="repeat_frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Daily", "Daily"),
                    ("Weekly", "Weekly"),
                    ("Monthly", "Monthly"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="repeat_week",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
