# Generated by Django 4.2.30 on 2026-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0017_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="actual_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_hours",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("Backlog", "Backlog"),
                    ("Planning", "Planning"),
                    ("In Progress", "In Progress"),
                    ("Review", "Review"),
                    ("Testing", "Testing"),
                    ("Blocked", "Blocked"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("On Time", "On Time"),
                    ("Delayed", "Delayed"),
                    ("Overdue", "Overdue"),
                ],
                default="Backlog",
                max_length=20,
            ),
        ),
    ]
