# Generated by Django 5.0.4 on 2026-07-10 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_remove_client_assigned_hqepls_and_more'),
        ('projects', '0016_remove_project_assigned_hqepl_and_more'),
        ('tasks', '0017_alter_task_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'target_date'], name='tasks_task_assigne_a8523f_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to', 'status'], name='tasks_task_assigne_b3b2bc_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['source_module', 'is_repeatable'], name='tasks_task_source__2f6210_idx'),
        ),
    ]
