# Generated by Django 5.0.4 on 2026-02-23 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visit_agenda", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="visitagenda",
            new_name="visit_agend_client__870a14_idx",
            old_name="visit_agenda_client_5a1b4a_idx",
        ),
        migrations.RemoveField(
            model_name="visitagendaitem",
            name="hqepl_rep",
        ),
        migrations.AddField(
            model_name="visitagendaitem",
            name="hqepl_reps",
            field=models.ManyToManyField(
                blank=True,
                related_name="visit_agenda_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
