# Generated by Django 5.1.1 on 2026-01-28 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_external_lead_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='client_org',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='project',
            name='external_lead',
        ),
        migrations.RemoveField(
            model_name='project',
            name='internal_lead',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overall_progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='team_members',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_sgm',
            field=models.ForeignKey(limit_choices_to={'role': 'SGM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['ADMIN', 'HQEPL']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HOLD', 'On Hold'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
    ]
