# Generated by Django 5.1.1 on 2026-01-29 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_client_org_project_client_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_lead',
            field=models.ForeignKey(limit_choices_to={'role': 'EXTERNAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='external_team',
            field=models.ManyToManyField(limit_choices_to={'role': 'EXTERNAL'}, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
