# Generated by Django 5.1.1 on 2026-02-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target',
            field=models.TextField(blank=True, null=True),
        ),
    ]
