# Generated by Django 5.0.4 on 2026-02-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_actionplan_actiontask'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontask',
            name='assign_file',
            field=models.FileField(blank=True, null=True, upload_to='action_tasks/assign/'),
        ),
        migrations.AddField(
            model_name='actiontask',
            name='completion_file',
            field=models.FileField(blank=True, null=True, upload_to='action_tasks/completion/'),
        ),
    ]
