# Generated by Django 5.0.4 on 2026-03-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_actiontask_assign_file_actiontask_completion_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_hierarchy",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
