# Generated by Django 5.0.4 on 2026-03-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_project_project_hierarchy"),
        ("visit_agenda", "0003_remove_visitagendaitem_tentative_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="actionplan",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="actionplan",
            name="visit_agenda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_plans",
                to="visit_agenda.visitagenda",
            ),
        ),
        migrations.AddField(
            model_name="actiontask",
            name="visit_agenda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="action_tasks",
                to="visit_agenda.visitagenda",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="senior_team",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "SENIOR"},
                related_name="senior_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
