# Generated by Django 5.0.4 on 2026-04-01 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_actionplan_updated_at_actionplan_visit_agenda_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="assigned_hqepl",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "HQEPL"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hqepl_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["ADMIN", "HQEPL", "MLS", "SGM"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
