# Generated by Copilot to add priority to ActionTask.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_flag_document_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='actiontask',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=10),
        ),
    ]