# Generated by Django 4.2.30 on 2026-07-09 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0015_actiontask_priority"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="assigned_hqepl",
        ),
        migrations.AddField(
            model_name="project",
            name="assigned_kayaara",
            field=models.ForeignKey(
                blank=True,
                db_column="assigned_hqepl",
                limit_choices_to={"role": "KAYAARA"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kayaara_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                limit_choices_to={"role__in": ["ADMIN", "KAYAARA", "MLS", "SGM"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
