# Generated by Django 4.2.30 on 2026-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_remove_project_assigned_hqepl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget_unit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("THOUSAND", "Thousand"),
                    ("LAKH", "Lakh"),
                    ("CRORE", "Crore"),
                ],
                default="LAKH",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="total_budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total budget amount",
                max_digits=15,
                null=True,
            ),
        ),
    ]
