# Generated by Django 4.2.30 on 2026-07-22 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0018_project_priority_projectmilestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("target", models.TextField(blank=True, null=True)),
                (
                    "default_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default budget for projects from this template",
                        max_digits=15,
                        null=True,
                    ),
                ),
                (
                    "budget_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("THOUSAND", "Thousand"),
                            ("LAKH", "Lakh"),
                            ("CRORE", "Crore"),
                        ],
                        default="LAKH",
                        max_length=10,
                    ),
                ),
                (
                    "default_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "estimated_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated project duration in days",
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("PHARMA", "Pharma"),
                            ("IT", "IT / Software"),
                            ("MANUFACTURING", "Manufacturing"),
                            ("CONSTRUCTION", "Construction"),
                            ("HEALTHCARE", "Healthcare"),
                            ("FINANCE", "Finance / Banking"),
                            ("EDUCATION", "Education"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Public templates are visible to all users; private only to the creator",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplateTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.TextField()),
                (
                    "assigned_role",
                    models.CharField(
                        blank=True,
                        help_text="Role hint for who should do this task (e.g. SGM, EMPLOYEE, EXTERNAL)",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("document", "Document"),
                            ("training", "Training"),
                            ("resource", "Resource"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                (
                    "start_date_offset",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of days from project start for the start date",
                    ),
                ),
                (
                    "target_date_offset",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of days from project start for the target date",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="projects.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["start_date_offset", "target_date_offset"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplateMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "due_date_offset",
                    models.PositiveIntegerField(
                        help_text="Number of days from project start when this milestone is due"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.projecttemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date_offset"],
            },
        ),
    ]
