# Generated by Django 5.0.4 on 2026-03-14 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_customuser_shortform"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="password_changed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="customuser",
            name="plain_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
