# Generated by Django 5.0.4 on 2026-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_customuser_password_changed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("HQEPL", "HQEPL"),
                    ("SGM", "SGM"),
                    ("EMPLOYEE", "Employee"),
                    ("CLIENT", "Client"),
                    ("EXTERNAL", "External"),
                    ("SENIOR", "Senior"),
                ],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
