# Generated by Django 4.2.30 on 2026-07-03 17:21

from django.db import migrations


def rename_hqepl_to_kayaara(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='HQEPL').update(role='KAYAARA')


def reverse_kayaara_to_hqepl(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    CustomUser.objects.filter(role='KAYAARA').update(role='HQEPL')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RunPython(rename_hqepl_to_kayaara, reverse_kayaara_to_hqepl),
    ]
