# Generated by Django 4.2.30 on 2026-07-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_rename_hqepl_role_to_kayaara"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("KAYAARA", "KAYAARA"),
                    ("MLS", "MLS"),
                    ("SGM", "SGM"),
                    ("EMPLOYEE", "Employee"),
                    ("CLIENT", "Client"),
                    ("EXTERNAL", "External"),
                    ("SENIOR", "Senior"),
                ],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
    ]
