# Generated by Django 4.2.30 on 2026-07-17 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="department_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HOD", "HOD"),
                    ("MANAGER", "Manager"),
                    ("EMPLOYEE", "Employee"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.department",
            ),
        ),
    ]
