# Generated by Django 4.2.30 on 2026-07-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_department_customuser_department_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("TASK_CREATED", "Task Created"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("CLIENT_CREATED", "Client Created"),
                    ("PROJECT_CREATED", "Project Created"),
                ],
                max_length=30,
            ),
        ),
    ]
