# Generated by Django 4.2.30 on 2026-07-18 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_alter_auditlog_action"),
        ("accounts", "0015_alter_auditlog_action"),
    ]

    operations = []
