# Generated by Django 4.2.30 on 2026-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_merge_20260718_1148"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_LOGIN", "User Login"),
                    ("USER_LOGOUT", "User Logout"),
                    ("FAILED_LOGIN", "Failed Login"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("TASK_CREATED", "Task Created"),
                    ("TASK_COMPLETED", "Task Completed"),
                    ("CLIENT_CREATED", "Client Created"),
                    ("PROJECT_CREATED", "Project Created"),
                    ("TASK_UPDATED", "Task Updated"),
                    ("TASK_DELETED", "Task Deleted"),
                ],
                max_length=30,
            ),
        ),
    ]
