# Generated by Django 4.2.30 on 2026-07-22 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_auditlog_action"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codename",
                    models.CharField(
                        db_index=True,
                        help_text="Dot-notation permission identifier, e.g. 'projects.create'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Human-readable name", max_length=200),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("projects", "Projects"),
                            ("tasks", "Tasks & Milestones"),
                            ("users", "Users & Roles"),
                            ("reports", "Reports & Analytics"),
                            ("clients", "Clients"),
                            ("organization", "Organization"),
                            ("workspace", "Workspace"),
                            ("notifications", "Notifications"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "ordering": ["category", "codename"],
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("KAYAARA", "KAYAARA"),
                    ("MLS", "MLS"),
                    ("SGM", "SGM"),
                    ("EMPLOYEE", "Employee"),
                    ("CLIENT", "Client"),
                    ("EXTERNAL", "External"),
                    ("SENIOR", "Senior"),
                    ("FREELANCER", "Freelancer"),
                    ("VENDOR", "Vendor"),
                    ("GUEST", "Guest"),
                ],
                default="EMPLOYEE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RolePermissionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(db_index=True, max_length=30)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("assigned", "Assigned"),
                            ("owned", "Owned"),
                            ("project", "Project"),
                            ("denied", "Denied"),
                        ],
                        default="denied",
                        help_text="Access scope for this permission",
                        max_length=20,
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_templates",
                        to="accounts.permission",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Permission Template",
                "verbose_name_plural": "Role Permission Templates",
                "ordering": ["role", "permission__category", "permission__codename"],
                "unique_together": {("role", "permission")},
            },
        ),
    ]
