# Generated by Django 5.0.4 on 2026-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_permission_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department_role',
            field=models.CharField(blank=True, choices=[('HOD_L1', 'HOD Level-1'), ('HOD_L2', 'HOD Level-2'), ('MANAGER_L1', 'Manager Level-1'), ('MANAGER_L2', 'Manager Level-2'), ('EMPLOYEE', 'Employee')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Super Admin'), ('ORG_OWNER', 'Org Owner'), ('ORG_ADMIN', 'Org Admin'), ('HOD_L1', 'HOD Level-1'), ('HOD_L2', 'HOD Level-2'), ('MANAGER_L1', 'Manager Level-1'), ('MANAGER_L2', 'Manager Level-2'), ('EMPLOYEE', 'Employee'), ('EXTERNAL', 'External'), ('SENIOR', 'Senior'), ('FREELANCER', 'Freelancer'), ('GUEST', 'Guest')], default='EMPLOYEE', max_length=20),
        ),
    ]
