# Generated by Django 5.0.4 on 2026-03-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("TASK_ASSIGNED", "Task Assigned"),
                    ("DDTME_SUBMITTED", "DDTME Submitted"),
                    ("DDTME_APPROVED", "DDTME Approved"),
                    ("DDTME_REJECTED", "DDTME Rejected"),
                    ("DDTME_EDIT_ALLOWED", "DDTME Edit Allowed"),
                    ("REPEAT_TASK_REMINDER", "Repeat Task Reminder"),
                    ("PROJECT_INCLUDED", "Project Included"),
                    ("VISIT_AGENDA_INCLUDED", "Visit Agenda Included"),
                    ("ACHIEVEMENT_AWARDED", "Achievement Awarded"),
                    ("ACTION_PLAN_NOT_SHARED", "Action Plan Not Shared"),
                ],
                max_length=32,
            ),
        ),
    ]
