# Generated by Django 5.1.1 on 2026-01-28 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_externalteam_role_alter_externalteam_client_org'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalteam',
            name='role',
        ),
        migrations.AddField(
            model_name='externalteam',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_external_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='externalteam',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
