# Generated by Django 5.1.1 on 2026-02-06 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_externalteam_role_externalteam_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assigned_sgm',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'SGM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='internal_team',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, related_name='internal_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
