# Generated by Django 5.1.1 on 2026-02-07 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_assigned_sgm_client_internal_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='assigned_sgm',
        ),
        migrations.AddField(
            model_name='client',
            name='assigned_sgms',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'SGM'}, related_name='assigned_clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
