# Generated by Django 5.1.1 on 2026-02-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_client_assigned_sgm_client_assigned_sgms'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalteam',
            name='credential_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='externalteam',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('hold', 'Hold'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
