# Generated by Django 5.0.4 on 2026-04-01 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_client_client_hierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="assigned_hqepls",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "HQEPL"},
                related_name="assigned_hqepl_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
