# Generated by Django 4.2.30 on 2026-07-09 18:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clients", "0012_client_assigned_hqepls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="assigned_hqepls",
        ),
        migrations.AddField(
            model_name="client",
            name="assigned_kayaara_users",
            field=models.ManyToManyField(
                blank=True,
                db_table="clients_client_assigned_hqepls",
                limit_choices_to={"role": "KAYAARA"},
                related_name="assigned_kayaara_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
