# Generated by Django 5.0.4 on 2026-03-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddtme", "0006_kpi_kpiupdate"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigtask",
            name="ddtme_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
