# Generated by Django 4.2.30 on 2026-05-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ddtme", "0009_bigtask_parent_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="bigtask",
            name="ryg_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RYG status: G, Y, R, or H",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="ddtmeadditionaltask",
            name="ryg_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RYG status: G, Y, R, or H",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="ddtmemonthlyobjective",
            name="ryg_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RYG status: G, Y, R, or H",
                max_length=2,
            ),
        ),
    ]
