# Generated by Django 5.1.1 on 2026-02-07 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def consolidate_project_teams(apps, schema_editor):
    ProjectTeam = apps.get_model('sgm', 'ProjectTeam')
    db_alias = schema_editor.connection.alias

    project_ids = (
        ProjectTeam.objects.using(db_alias)
        .values_list('project_id', flat=True)
        .distinct()
    )

    for project_id in project_ids:
        rows = list(ProjectTeam.objects.using(db_alias).filter(project_id=project_id).order_by('id'))
        if not rows:
            continue
        keeper = rows[0]
        employee_ids = [row.employee_id for row in rows if row.employee_id]
        if employee_ids:
            keeper.internal_members.add(*employee_ids)
        if len(rows) > 1:
            ProjectTeam.objects.using(db_alias).filter(id__in=[r.id for r in rows[1:]]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_target'),
        ('sgm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectteam',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='external_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EXTERNAL'}, related_name='sgm_external_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='internal_members',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'EMPLOYEE'}, related_name='sgm_internal_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(consolidate_project_teams, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectteam',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sgm_team', to='projects.project'),
        ),
        migrations.RemoveField(
            model_name='projectteam',
            name='employee',
        ),
    ]
