# Generated by Django 5.0.4 on 2026-02-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meeting_agenda",
            "0002_rename_visit_agenda_client_5a1b4a_idx_visit_agend_client__870a14_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meetingagendaitem",
            name="tentative_time",
        ),
        migrations.AddField(
            model_name="meetingagendaitem",
            name="end_time",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="meetingagendaitem",
            name="start_time",
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
