# Generated by Django 5.0.4 on 2026-03-30 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_client_client_hierarchy"),
        ("meeting_agenda", "0003_remove_visitagendaitem_tentative_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingAgendaLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_date", models.DateField()),
                ("items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_agenda_logs",
                        to="clients.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meeting_agenda_logs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_agenda",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="meeting_agenda.meetingagenda",
                    ),
                ),
            ],
            options={
                "ordering": ["-visit_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["client", "visit_date"],
                        name="meeting_age_client__69dcf2_idx",
                    )
                ],
            },
        ),
    ]
