# Generated by Django 4.2.30 on 2026-07-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "meeting_agenda",
            "0006_rename_meeting_age_client__870a14_idx_meeting_age_client__ad5bfe_idx_and_more",
        ),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="meetingagenda",
            new_name="meeting_age_client__ad5bfe_idx",
            old_name="meeting_age_client__870a14_idx",
        ),
        migrations.RenameIndex(
            model_name="meetingagendalog",
            new_name="meeting_age_client__6d708b_idx",
            old_name="meeting_age_client__69dcf2_idx",
        ),
        migrations.AddField(
            model_name="meetingagendalog",
            name="end_time",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
        migrations.AddField(
            model_name="meetingagendalog",
            name="start_time",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
