# Generated by Django 4.2.30 on 2026-07-11 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "meeting_agenda",
            "0007_rename_meeting_age_client__870a14_idx_meeting_age_client__ad5bfe_idx_and_more",
        ),
    ]

    operations = [
    ]
